[package]
name = "universe"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "2"
hyper = "0"
kvm-ioctls = "0"
reqwest = "0"
sallyport = "0"
serde = "1"
tokio = { version = "1", features = ["full"] }
