name: "Build"
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: nix-shell --run "build"
    - uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: target/doc
        target-folder: rust
